baseURL: "https://iwr2023.github.io/"
languageCode: en-us
title: IWR 2023
theme: ananke
menu:
  main:
    - identifier: sponsors
      name: Sponsors
      weight: -110
    - name: getting started
      post: <span class='alert'>New!</span>
      weight: -100
params:
  mainSections:
    - posts
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
