baseURL: "https://iwr2023.github.io/"
languageCode: en-us
title: IWR 2023
theme: ananke
menu:
  main:
    - identifier: sponsors
      name: Sponsors
      weight: -110
    - identifier: iwr2023
      name: IWR 2023
      weight: -90
params:
  mainSections:
    - posts
  custom_css:
    - custom.scss
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
