baseURL: "https://iwr2023.github.io/"
languageCode: en-us
title: IWR 2023
theme: ananke
menu:
  main:
    - identifier: iwr2023
      name: IWR 2023
      weight: 20
    - identifier: about
      name: About
      weight: 10
params:
  mainSections:
    - posts
  custom_css:
    - custom.scss
  countdownDate: May 24 2023 12:00:00
  site_logo: "images/iwr_logo.JPG"
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
markup:
  goldmark:
    renderer:
      hardWraps: true
